# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: default_username
      MONGO_INITDB_ROOT_PASSWORD: default_password
    networks:
      - recommendation-engine-net
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: default_username
#      ME_CONFIG_MONGODB_ADMINPASSWORD: default_password
#    networks:
#      - recommendation-engine-net

networks:
  recommendation-engine-net:
    name: recommendation-engine-net